### ISSUE TITLE
Badges are blurry

### ISSUE THREAD

**Issue by 1davi** [AnemoneTeam/Anemone#22]
The badges are slightly blurry when using a custom background.

![badgebug](https://cloud.githubusercontent.com/assets/14959546/10266182/eca7d946-6a27-11e5-9738-b049e20292c4.png)

**Comment by coolstar** [comment]
Can you try the ModernBadges theme from https://coolstar.org/publicrepo and see if you get the issue on that theme?

**Comment by 1davi** [comment]
Tested and the same problem happens, here is a comparison:

![badgebug2](https://cloud.githubusercontent.com/assets/14959546/10269063/33d43b92-6aa1-11e5-975d-7dc8d9cd4b97.png)

**Comment by cj81499** [comment]
It looks like it's half a pixel out of place or something. Maybe it's an issue because of @2x vs @3x?

**Comment by coolstar** [comment]
@cj81499 possibly. It's hard to tell. @1davi which device do you have?

**Comment by cj81499** [comment]
Yeah. It was just a guess.

**Comment by coolstar** [comment]
This is how ModernBadges looks on my iPhone 6 here. While I haven't zoomed in to nitpick, it doesn't look blurry at all to the naked eye 
![image](https://cloud.githubusercontent.com/assets/1431548/10269831/0df26bf2-6a96-11e5-88a6-18bda2ad24b9.jpg)

**Comment by cj81499** [comment]
I think I just figured it out. iOS icons move around based on how you're holding your device because of parallax. This includes the badges. It's probably just moving at a sub-pixel level and causing the lines to look not pixel perfect. Disabling Parallax fixed the issue for me.

**Comment by coolstar** [comment]
@cj81499 ah. I disable parallax first thing after jailbreaking here. Worthless feature that just causes lag lol.

**Comment by cj81499** [comment]
Haha. That explains it. What are you using to disable it?

**Comment by coolstar** [comment]
ClassicFolders

**Comment by cj81499** [comment]
Is there any other tweak to disable it? No offense, but I've had issues with ClassicFolders in the past and they still haven't been fixed so I won't use it.

**Comment by coolstar** [comment]
@cj81499 they haven't fixed? I'm the developer of ClassicFolders :P

**Comment by cj81499** [comment]
Yeah. I know, thats why I said no offense :P

I actually made a post on reddit about the issues [here](https://www.reddit.com/r/jailbreak/comments/316quv/what_i_want_added_to_classicfolders/). You commented and said you would fix/add some of the problems/requests I had, but didn't for most of them.

**Comment by 1davi** [comment]
I didn't know parallax affected the badges, I disabled it now and the problem is solved :)

But in the screenshot @coolstar posted the badge is slight different, there's a dark line in the bottom:
Or maybe that's just the jpeg compression?

![hm](https://cloud.githubusercontent.com/assets/14959546/10269996/5daf8556-6abb-11e5-8e7a-48474f42e4c4.png)

**Comment by cj81499** [comment]
@coolstar is [this](https://twitter.com/coolstarorg/status/650762416318361600) about me? I said they (as in the problems) weren't fixed. Not that they (as in the developer) didn't fix them.

**Comment by cj81499** [comment]
@1davi Glad you got it figured out. No clue what the line is from. What did you use to disable Parallax?

**Comment by coolstar** [comment]
@cj81499 yeah lol

**Comment by cj81499** [comment]
Haha sorry about the misunderstanding. Anything to say about the problems I had and things I wished the tweak had?

**Comment by 1davi** [comment]
@cj81499 I enabled the "Reduce Motion" option in the settings.

**Comment by 1davi** [comment]
@coolstar Btw, can I make you a question? How do I put a shadow on the icon labels? Because the example plist from here is not working: https://github.com/AnemoneTeam/Anemone/wiki/Icon-Labels

**Comment by cj81499** [comment]
@1davi Ok thanks

**Comment by cj81499** [comment]
@coolstar If we're asking about the Label Settings Keys, is there any way to make the text outlined in a certain color (for example, white text with a black border around it)?

**Comment by coolstar** [comment]
@cj81499 it is currently not possible to add a text outline just yet to icon labels. 

@1davi hmm, interesting. which device do you have? We had to turn off a few options on the icon labels for 32 bit devices for performance reasons. However, shadows should still work regardless.

**Comment by cj81499** [comment]
@coolstar Any chance you could add something like that?

**Comment by coolstar** [comment]
@cj81499 I'll take a look at it. However, as usual, if it degrades performance on older devices even a bit (and can't be optimized so that doesn't happen) I can't do it.

**Comment by 1davi** [comment]
@coolstar iPhone 5C

**Comment by cj81499** [comment]
@coolstar sounds good! Hope you can figure something out.

**Comment by 1davi** [comment]
@coolstar I've found out why the shadow was not working, in your example plist the key "ShadowColor" is missing, after placing it in the plist and setting the color to black the shadow appeared.

**Comment by coolstar** [comment]
@1davi ah, whoops. I'll fix the wiki.

**Comment by 1davi** [comment]
I think you can close this issue. Thanks for creating Anemone and keep up the good work :)
