### ISSUE TITLE
Folder Icons masks can only be made smaller, not larger.

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#27]
Applying an icon mask should make the folders have the same shape, but if the mask extends past the normal corner radius of the folder, the folder's shape is not changed.

![image](https://cloud.githubusercontent.com/assets/9152032/10327868/9b4b8836-6c7a-11e5-9d0c-3a17a48e8c8c.jpg)

**Comment by coolstar** [comment]
Please try the new folder icon API in Anemone 1.1-30 and let me know if it fixes this:

https://github.com/AnemoneTeam/Anemone/wiki/Folder-Icons

**Comment by cj81499** [comment]
@coolstar The way you have it working now isn't really better. If you want a mask that is more complex than a rounded corner, that is no longer possible. For example this used to work and now doesn't.

![image](https://cloud.githubusercontent.com/assets/9152032/10716979/1c231790-7b20-11e5-9347-70c7afeb4136.jpg)

**Comment by cj81499** [comment]
Also, the folder mask appears as if it should be rounded in the preview within Anemone, so either the preview is wrong, or the homescreen is.

Edit: thought I'd show what I mean.

![image](https://cloud.githubusercontent.com/assets/9152032/10717001/b8cf2e4e-7b20-11e5-8aec-740b4967f6f6.jpg)

**Comment by coolstar** [comment]
@cj81499 yes, unfortunately it's no longer possible due to people with 9001 folders on their home screen complaining about it lagging

**Comment by cj81499** [comment]
Is there any way to get this back with an option in an info .plist? I miss it.

**Comment by coolstar** [comment]
sure I can add that

**Comment by cj81499** [comment]
Great! Ideally, the .plist implemtation would work with making larger masks (like the one I was using when I first made the post) too.

**Comment by coolstar** [comment]
Can you see if this issue is now fixed with FolderLegacyMask boolean set to true in Info.plist?

FolderLegacyMask restores the old behavior.

**Comment by cj81499** [comment]
Worked perfectly. Will this also work with larger masks (such as the one this post was originally made about)?

**Comment by cj81499** [comment]
Just checked. Larger masks work, however the overlay from clicking it is off. Here is a picture to explain:

![image](https://cloud.githubusercontent.com/assets/9152032/10727751/a0dafff6-7bb2-11e5-9f90-9e7ca099d006.jpg)

**Comment by coolstar** [comment]
Can you try Anemone 1.1-39 from the fast ring repo? That update should resolve this issue.

**Comment by cj81499** [comment]
Nope. Still happening. If it helps, iPhone 6, iOS 8.4

The mask I'm using is called Barely Rounded and is available on my repo: https://cj81499.github.io

**Comment by coolstar** [comment]
Does this issue still happen in Anemone 1.1-67?

**Comment by cj81499** [comment]
iPhone 6 is no longer jailbroken, so I couldn't test with it, but It still didn't work on my iPod 5, iOS 9.0.2

**Comment by coolstar** [comment]
Can you give this a try on the newest Anemone version and iOS 9.3.3 and let us know if it's fixed?

**Comment by coolstar** [comment]
This has been fixed a while back so closing. If the issue is still present, this will be re-opened.

**Comment by cj81499** [comment]
Just seeing this now. The issue is still there. 9.1, iPhone 6.

**Comment by coolstar** [comment]
Ok. I've tested Barely Rounded and have made a fix for the folder icon overlay mask issue. It'll be in the next nightly.

**Comment by coolstar** [comment]
Fixed in 1.1-367
